language: node_js
dist: trusty
git:
  depth: 1
cache:
  edge: true
  directories:
    - node_modules
    - "$(npm root -g)"
    - "$(npm config get prefix)/bin"
branches:
  only:
    - master
    - stage
    - test
    - dev
env:
  global:
    # CODECLIMATE_REPO_TOKEN=[secure]
    - secure: "p/6P+aA5txrDxC6YnlZ/Lhu1uKGOsQa4JGN7KLYoghXnQZGKnZPIQu3T5ZtpqRSUfAIqUpmafPo4BU+z/KzPfMZaEkXBBinztBDgfbw+W9qLrA+AGGsgVmGPYrSw09gOXSbXGHxIOpuUxi6GW5+FaowZG4l2D1Zti20DvjwfzKysD780JDH5reAvsJ4k6ZPVwMOHxtXlXAunkJCCSoEyomDff8XTCGcwrDZAx0At1uApYiikTYJfrqugYul4Z+WoqBOe2A8jA99cWNM44VD+rysfCz4en9a7b3fDY497rVUKFSo3J8d6WFzIT+ioyqgXnDjkJlR28MPV0Yq+xSxS1A4rP0AY3sg/6btu7EMxfiehAA9Mlfa8l6n3Y18SaDygp92f4gYGkloCDpUXabL2pSBPfCNkHozcpS27W42SpKobe/T8w+Hp9HxzArWOhD39LQGzIQCqFzkwnzHgZ/5agYgwGK3gYKRYUDu51rbzqNuUs6Xgy92iqmpnivXkdIW2Wr4bfSKn8l28UBTJuhMRlJAZAs11oVdLXoqmge2sbZ5UlzO0gjoNw65rfBGkZH/bt4fetjZApEkoKn4KT6RrHLQol7KqXhrctOH5sHi9IX6/d+pnpKXKZsGR3T6ySWua8zrUBBUewaY+keDPOF651iBj1BXen1eeEMusiZRURnI="
    # SNYK_API_TOKEN=[secure]
    - secure: "rIUyMjTfF6vtxYwIIOMj57Rm3jGfQSp7eB/y6ncXJkfYjO2OEJixAv0/Rpg9VDtF6FNDy40hYKH2SJ7201uzjWcMQi9YHpKLri17lKbuKX4+CkPEJzgEHwt92nYylEgaHEvuVmwa+JgLvqemTzzqLeldd0ao2h9Z91/fMQEc+GIa9ioE00ZCpN/ilYN/MRwtiNkI3YzGAu8CYJ/kDa76y0RlEeUEby4cFv2iAqEHvH2n/RQNAPvlm6DSUHfJ+xuwQCzCcNQd4h9a8Hr/gRIeT1DkRn92rsTZXhxZO9rHkHo2wQGiInqoOdjsDALiAQBjGj1ncoiMb2pYW1GqOcA8Wu6IUaIJPSuLMdjhYieAn7XEVkQHJZPWTNbPLzLazE8puextRIHRwxgprBAtiWjfZMD38t59pbeTxvJh4Y1u0jzZPFZzOzdVej5EN9kdXYGdvKY1f2NC8O/TuEtIIejVgsJ6shT3k+XkKdG4KhRlGbjn2aEAOW7se588FT0M/rGYyBdSf1iImCIFBfs7IB7cK2BBChfEefRKSyYtCjVydXjVETqp1JRZ0Ra9ItXvJSNiKj36Vzj9TUsw6POa1MjVFZwpBIwV2DBNpjg+toquH48xA09xoLH1IVbC9ybOIXHfBsgAbE/+gnH5AEMSOhg8ElRu2x5h36F5EORc6R2CQtA="
    # AWS_DEFAULT_REGION=[secure]
    - secure: "4apRCaQOEqX1LzY+foXXMhMvEoC72gQ0X32J6nvsSEVQMiO3JZLC8jGpYjivqtcEFun3B7gTQO2UdNLxhd0N3/gaM4RdFE5+Sk/5ifpitf9D2byi4uTahXedx7BCd24YH7TaFNHG3SAB78+qGs5OEKlq9dqI6I8Uj7hJDGKVUunyFsiqy9umJ9wj8RJ7UOPJcNfN9KEOwVuoYsy9z0BcL56NSsLm1H4C6qY32/8Wt44lgYU2I76YDTtxh4cIYpry1wSXq/SmVkN0ef+Lcgw8OEooEQ3trpvrwFyifoOIuEaDxNPTK0I5nlrKmJghwUHZGJQNYA0TlSdkh5jPlOvfbMc5lM/qnNDbmXFbx2Figozk81ow5vqCAtth3C2p9bSSQwzsc050YFngZm7tidaYutvhuBCQm2eXWL5PNxyES90MNaGYqgmPKrlMG7Gh+VmScY5VcwAkEfeq/llrY9BPOsrztv2fYFUlmOOtOt3JYhowHmb5WY+AQlYDP5Ya5d9osKzbxrswCnGeswlTBgPjmXdVOlh9nttkkN3YENK1/BQju+qIt2rg7OU4Li2j17Fyk4tK6qeoVc8ysRTCJgPyKyQCaNEX0YhK+LVGsnpYqVJXRGsiiv0VRn0uTyLsRw2jPS4ZyprFBvfYLK1XMg91N36KkuY4iXyTylJghsf+zAc="
    # AWS_ACCESS_KEY_ID=[secure]
    - secure: "dhacCj56uHOL85YSpI30HAsDZDLD00ZvMdIoG/HDumsMEoj87sf7+8kdvcXFYkeXX9NuxLRtQGRWXDVtTSC5WX+db9PrsN/F5GM93zm9zdXdUzN8CVegSaa0y2MG5iIe2WHkGKR6DB0j2f1U1NX8BWcFJ/Y31JEfVLHxWigYxEGM23p0oo28PoNa/ECMIhXfvnOfV65B6I5/p95iATQhFJfz5hPZPwY2AsPK8NTw4NgectKhW/vC8lUPXk6qfsjuSlT1bK/FYWiHJEPvBUCYegWT8E7WFiEWu44StNkd4Jovnn0zBP2Tdtu3KoqFG+1ZaicoRZ/uigP1USm9OoTspiTSUR2x3BTreD2H8lLXIsOlqB+LLgj9wJOACeNJN0ZI9QCytAr5BMvYopR4x+ycJA41g/1VQ6hdlZNBoDRP8IPOG1jyI3H38u9uOhf8YBql6G3wtpw4LN2aZfbRzU6IC1nWPk2bnWEl63CmPmtBvrKJzlZD8h/qU7WmkbOqXGcc0G//t+LHx8fJUOUxFJl9FD4XZ6Wn5twmflshXwKDmmzwvlnQBumN34efXCArsNqSdySAg1pGeUEz13S35+XzG5k8wNT05cfuQBptCRMm8alLwPzKgZ1U/hLn4WkLha8FKAQF5aKuP5gWnSb3dBYOnsOnrrIdRkVwC8dGLxgtykc="
    # AWS_SECRET_ACCESS_KEY=[secure]
    - secure: "KL6vHY+I0xXiGbejWA4TvIFE2FpWlYoHl1VX/glQFmNfQw0WFdSV2mhfmhVKcB0RuKORK38G+dtqCQdFjUjsqPUNTS1EDZMJaI7Bk+nEOtH7GDCRg8EHQ7C1LdXjpHXs8nRNN51OjJbUW5FIWvUaifOJohmWyZS6YK1ctonC3zFe23Zlzh5qGR0YuG6RJ0WsYKTVlprzez9O7qrFWJqjB8jIZQDofstT4zrmeBu96roLVzxFSiZJbFE0aswWAcd+ePdlYd6Dh0IXc9UcqJF1jctjMjCVAK032teZhoZg9Rx69cDN1T4IaQ99bsP6CJl4cB9lUy8h2aFVqVhsGwcmD5SOS1oKQ7IrZryzmf4RjpCGIRcySUerULymsr/L/JFU+7kr5KTRRtUMEDUishnFwpt8otRi6+7xAZ7LTsAHie2Ub0zrP8zMzMYojscAzE1DlNAW1eO7Fdsg0hwddRceoJk0z8I7AockpGFISiJVAbjdv/TDqR8RmA4kBayOVFGUZNem4Iiz/3MCbHcgmDLgPNipUk5uV2DyRlvTPNfRvR4V5psS/22GzQxDjb4h4Xs8qmkOy1ZCNOwkBHoPRRRNCK7OOsqq1qSHpuWeNTq2WDM2NQF5uDcM8FeIT+t75duhNSaLn98tgEekazWGEjm/KvkwdzdGJQhvBXd4rQ4s/fo="

stage: "Run Unit Tests :clipboard:"
node_js:
  - 6
  - 8
before_install:
  - bash bin/travis-init.sh
script:
  - recink run unit -c recink-codeclimate -c recink-snyk
