language: node_js
sudo: required
node_js:
  - '4.3'
  - '6.2'
cache:
  edge: true
  directories:
    - $(npm root -g)
    - node_modules
    - deep_modules
    - $(npm config get prefix)/bin
branches:
  only:
    - master
    - dev
    - stage
    - test
before_install:
  - cp bin/test/package.json .
after_success:
  - npm run coverage
env:
  matrix:
    - TEST_SUITE=backend
    - TEST_SUITE=frontend
notifications:
  slack:
    secure: 
      eIsYTQtlG5d/GGPu4JBrvOCEVqwxGirqkOVl+D3UZGWLECzi3a/k7pmDOr41kDueWZAiM5i6c8RjvX/ngyddPoo/7WzHxxkeiukQJlb/PLWQpTU8/Wado3OQNy3rNTo9DJlQdO03o2EedQbb6vb3LaU91vawScPQmBPIZT2Gfm1NV7xxOEzXbM+asxNfM5CHCV415nfgKELgP0Xi+Nn52SgwTRBaM+chSivdbOKqtC/svb8mCCk1u5dBY1XWM5PmdgipxUn304ETR1rQwbQASkUXV6nixAGzZLkV1B8sDliMLaI0ay2Eu6/JmEHULPNi/NgKhG07hZNGpYLASFl7vTgU6ePanj/oSKpUFPrXj5jUI5TVbQ9b+63yMzop31d3b+3YhAZaFHf41p6+P2YK3QzaL4HA4kTDBARknM293zT1KC8wlKRHLKexCqc2+mgK7RTDCn8AFAxnuYcaMTGZeDPUTwjlrOuVUnEdn8OE6vPs8DPbV9UIXMLj72qzqj8aL/KtVWwr73vugSGg+UExZuujVminBZopmFcIHRme5AW33wMbXpIniw+oW6ZXUftN3sil5jTvp/vTB0aad3Odu1sqaMUciBKlQL9rR6hKhAh3S6wFCCJBH+t38ImNm5QIlu227KTEhxw/TZVKBHUKUIEFyUELlpAAU+pT1w/3BAU=
